# SAP Alert Notification Service 
alert_notification:
  servicePlanName: free
  parameters:
    configuration:
      actions:
      - name: send-email
        properties:
          destination: john.doe@example.org
        state: ENABLED
        type: EMAIL
      