apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: keep
  name: {{ template "capApplicationVersionName" . }}-brk-cred
type: Opaque
data:
{{- if and .Values.broker.credentials.user .Values.broker.credentials.password }}
  credentials.json: {{ printf "{\n \"%s\" : \"%s\" \n}\n" .Values.broker.credentials.user .Values.broker.credentials.password | b64enc }}
{{- else }}
  ERROR-.broker.credentials.user-or-.broker.credentials.password-missing: 
{{- end }}