apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "susaas-srv.fullname" . }}
  labels: {{- include "susaas-srv.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{- include "susaas-srv.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ default "router" .Values.global.router.name }}
              app.kubernetes.io/instance: {{ .Release.Name }}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app: istio-ingressgateway
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
